# Generated by Django 4.0.3 on 2022-03-19 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_review_driver_alter_review_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_reviewer',
            new_name='is_driver',
        ),
        migrations.RemoveField(
            model_name='review',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='review',
            name='passenger',
        ),
        migrations.AddField(
            model_name='review',
            name='review_recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Review_Recipient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
