# Generated by Django 4.0.3 on 2022-03-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='car',
        ),
        migrations.AddField(
            model_name='trippassenger',
            name='seats_booked',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
