# Generated by Django 4.0.3 on 2022-03-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_rename_available_seats_trip_total_passenger_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
