# Generated by Django 4.0.3 on 2022-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
