# Generated by Django 4.0.3 on 2022-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
