# Generated by Django 4.0.3 on 2022-05-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0002_checkin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='check-ins/'),
        ),
    ]
