# Generated by Django 4.0.3 on 2022-03-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0002_checkin_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
